languageCode = "ja"
hasCJKLanguage = "true"
title = "kglabo.com"
baseurl = "https://yu-kgr.github.io/kglabo/"
googleAnalytics = "UA-89893813-1"
enableRobotsTXT = "true"
theme = "hugo-theme-solit"

[params]
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Audiowide" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Audiowide" # Optional, Override logo font.
